"""Render a redacted PostgreSQL/Redis operations evidence summary.

This script only reads explicit JSON reports that were already generated by
other checkers. It does not read `.env`, connect to PostgreSQL or Redis, start
services, SSH to a server, inspect logs, or echo private target values.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
from typing import Any, Iterable, Mapping


for stream in (sys.stdout, sys.stderr):
    if hasattr(stream, "reconfigure"):
        stream.reconfigure(encoding="utf-8", errors="replace")


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.export_acceptance_evidence import redact_data, redact_text  # noqa: E402


POSTGRES_REDIS_OPS_SUMMARY_VERSION = "postgres_redis_ops_summary.v1"
BAD_STATUSES = {"blocked", "failed", "unknown", "skipped", "not_checked", "missing"}
DEGRADED_STATUSES = {"degraded", "warning"}
URL_PATTERN = re.compile(r"https?://[^\s`'\"<>()\[\]{}|]+", re.IGNORECASE)
IPV4_PATTERN = re.compile(
    r"\b(?:(?:25[0-5]|2[0-4]\d|1?\d?\d)\.){3}(?:25[0-5]|2[0-4]\d|1?\d?\d)\b"
)


SECTION_LABELS = {
    "ops_status": "PostgreSQL/Redis declarations",
    "live_probe": "Live PostgreSQL/Redis probe",
    "recovery_record": "Stateful recovery record",
}


def _as_mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _clean_text(value: Any) -> str:
    text = redact_text(str(value if value is not None else ""))
    text = URL_PATTERN.sub("[REDACTED_URL]", text)
    text = IPV4_PATTERN.sub("[REDACTED_IP]", text)
    return text.replace("\r", " ").replace("\n", " ").strip()


def _status(value: Any) -> str:
    return str(value or "unknown").strip() or "unknown"


def _safe_reason_item(section: str, item: Mapping[str, Any]) -> dict[str, Any]:
    key = item.get("env_var") or item.get("key") or item.get("field") or item.get("check")
    return {
        "section": section,
        "key": _clean_text(key or section),
        "finding": _clean_text(item.get("finding") or item.get("reason") or "Section did not pass."),
        "value_echoed": False,
    }


def _reason_items(section: str, report: Mapping[str, Any], key: str) -> list[dict[str, Any]]:
    items = []
    for item in _as_list(report.get(key)):
        if isinstance(item, Mapping):
            items.append(_safe_reason_item(section, item))
    return items


def _declaration_statuses(report: Mapping[str, Any]) -> dict[str, str]:
    declarations = _as_mapping(report.get("declaration_statuses"))
    return {
        str(key): _status(value)
        for key, value in sorted(declarations.items())
        if str(key).startswith("ZHIXING_")
    }


def _live_probe_details(report: Mapping[str, Any]) -> dict[str, Any]:
    sections = _as_mapping(report.get("sections"))
    postgres_container = _as_mapping(sections.get("postgres_container"))
    redis_container = _as_mapping(sections.get("redis_container"))
    postgres_ports = _as_mapping(postgres_container.get("ports"))
    redis_ports = _as_mapping(redis_container.get("ports"))
    postgres_mounts = _as_mapping(postgres_container.get("mounts"))
    redis_mounts = _as_mapping(redis_container.get("mounts"))
    return {
        "postgres_container": {
            "status": _status(postgres_container.get("status")),
            "state": _clean_text(postgres_container.get("state")),
            "health": _clean_text(postgres_container.get("health")),
            "persistent_mount": bool(postgres_mounts.get("expected_destination_present")),
            "public_port_bindings": len(_as_list(postgres_ports.get("public_bindings"))),
        },
        "redis_container": {
            "status": _status(redis_container.get("status")),
            "state": _clean_text(redis_container.get("state")),
            "health": _clean_text(redis_container.get("health")),
            "persistent_mount": bool(redis_mounts.get("expected_destination_present")),
            "public_port_bindings": len(_as_list(redis_ports.get("public_bindings"))),
        },
        "postgres_pg_isready": _status(_as_mapping(sections.get("postgres_pg_isready")).get("status")),
        "redis_ping": _status(_as_mapping(sections.get("redis_ping")).get("status")),
        "redis_appendonly": _status(_as_mapping(sections.get("redis_appendonly")).get("status")),
    }


def _recovery_details(report: Mapping[str, Any]) -> dict[str, Any]:
    summary = _as_mapping(report.get("record_summary"))
    checks = _as_mapping(report.get("checks"))
    return {
        "mode": _clean_text(summary.get("mode")),
        "affected_services": [
            _clean_text(item)
            for item in _as_list(summary.get("affected_services"))
            if _clean_text(item)
        ],
        "owner_roles_present": summary.get("owner_roles_present", 0),
        "action_count": summary.get("action_count", 0),
        "data_safety": _status(_as_mapping(checks.get("data_safety")).get("status")),
        "post_recovery_health": _status(_as_mapping(checks.get("post_recovery_health")).get("status")),
        "observed_metrics": _status(_as_mapping(checks.get("observed_metrics")).get("status")),
    }


def _section_summary(
    *,
    name: str,
    report: Mapping[str, Any] | None,
    required: bool,
) -> dict[str, Any]:
    if report is None:
        status = "not_checked" if required else "missing"
        return {
            "status": status,
            "required": required,
            "evidence_present": False,
            "label": SECTION_LABELS[name],
            "version": "",
            "declaration_statuses": {},
            "details": {},
            "blocked_reasons": [
                {
                    "section": name,
                    "key": f"{name}_json",
                    "finding": f"{SECTION_LABELS[name]} JSON was not provided.",
                    "value_echoed": False,
                }
            ]
            if required
            else [],
            "degraded_reasons": [],
        }

    details: dict[str, Any] = {}
    if name == "live_probe":
        details = _live_probe_details(report)
    elif name == "recovery_record":
        details = _recovery_details(report)

    return {
        "status": _status(report.get("status")),
        "required": required,
        "evidence_present": True,
        "label": SECTION_LABELS[name],
        "version": _clean_text(report.get("version")),
        "declaration_statuses": _declaration_statuses(report),
        "details": details,
        "blocked_reasons": _reason_items(name, report, "blocked_reasons"),
        "degraded_reasons": _reason_items(name, report, "degraded_reasons"),
    }


def _overall_status(sections: Mapping[str, Mapping[str, Any]]) -> str:
    statuses = [_status(section.get("status")) for section in sections.values()]
    if any(status in BAD_STATUSES for status in statuses):
        return "blocked"
    if any(status in DEGRADED_STATUSES for status in statuses):
        return "degraded"
    return "passed"


def _decision(status: str) -> str:
    if status == "passed":
        return "go_for_m1_stateful_ops"
    if status == "degraded":
        return "conditional_go_for_m1_with_recorded_stateful_limits"
    return "no_go_for_stateful_ops"


def _collect_reasons(sections: Mapping[str, Mapping[str, Any]], key: str) -> list[dict[str, Any]]:
    collected: list[dict[str, Any]] = []
    for name, section in sections.items():
        collected.extend(
            item
            for item in _as_list(section.get(key))
            if isinstance(item, Mapping)
        )
        status = _status(section.get("status"))
        if key == "blocked_reasons" and status in BAD_STATUSES and not section.get(key):
            collected.append(
                {
                    "section": name,
                    "key": name,
                    "finding": f"{SECTION_LABELS[name]} status is {status}.",
                    "value_echoed": False,
                }
            )
        if key == "degraded_reasons" and status in DEGRADED_STATUSES and not section.get(key):
            collected.append(
                {
                    "section": name,
                    "key": name,
                    "finding": f"{SECTION_LABELS[name]} status is degraded.",
                    "value_echoed": False,
                }
            )
    return collected


def build_postgres_redis_ops_summary_report(
    *,
    ops_status: Mapping[str, Any] | None = None,
    live_probe: Mapping[str, Any] | None = None,
    recovery_record: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Build a redacted stateful-service operations summary."""

    sections = {
        "ops_status": _section_summary(name="ops_status", report=ops_status, required=True),
        "live_probe": _section_summary(name="live_probe", report=live_probe, required=True),
        "recovery_record": _section_summary(name="recovery_record", report=recovery_record, required=True),
    }
    status = _overall_status(sections)
    report = {
        "version": POSTGRES_REDIS_OPS_SUMMARY_VERSION,
        "status": status,
        "decision": _decision(status),
        "policy": {
            "reads_dotenv": False,
            "connects_database": False,
            "connects_redis": False,
            "connects_ssh": False,
            "starts_services": False,
            "reads_logs": False,
            "reads_database_rows": False,
            "reads_redis_keys": False,
            "does_not_echo_private_values": True,
        },
        "section_statuses": {
            name: section["status"]
            for name, section in sections.items()
        },
        "sections": sections,
        "blocked_reasons": _collect_reasons(sections, "blocked_reasons"),
        "degraded_reasons": _collect_reasons(sections, "degraded_reasons"),
        "claim_boundaries": {
            "can_claim": [
                "PostgreSQL/Redis declarations, live probe and recovery record are tied together in one evidence summary."
                if status in {"passed", "degraded"}
                else "Stateful-service evidence is not complete enough for a production readiness claim."
            ],
            "cannot_claim": [
                "Managed HA, automatic failover, PITR, multi-AZ resilience or long-duration soak stability.",
                "Successful real customer recovery, real payment, inventory lock, ticketing or fulfillment.",
                "Database row correctness or Redis key correctness; this summary never reads those values.",
            ],
        },
        "next_actions": _next_actions(status, sections),
        "not_proven_by_this_summary": [
            "This summary validates existing JSON evidence only; it does not execute live checks itself.",
            "A single-server Compose setup can support M1 controlled trial evidence but is not full production HA.",
            "Raw logs, screenshots, database dumps, Redis key dumps, .env files and secret values must stay outside Git.",
        ],
    }
    safe_report = redact_data(report)
    return safe_report if isinstance(safe_report, dict) else report


def _next_actions(status: str, sections: Mapping[str, Mapping[str, Any]]) -> list[str]:
    actions: list[str] = []
    if sections["ops_status"]["status"] in BAD_STATUSES:
        actions.append("Fill stateful-service operations declarations and rerun check_postgres_redis_ops_status.py.")
    if sections["live_probe"]["status"] in BAD_STATUSES:
        actions.append("Run collect_postgres_redis_live_probe.py against the target server after services are up.")
    if sections["recovery_record"]["status"] in BAD_STATUSES:
        actions.append("Complete a private PostgreSQL/Redis recovery record and validate it with check_postgres_redis_recovery_record.py.")
    if status == "degraded":
        actions.append("Record accepted M1 limitations, especially single-node Compose and any public-port/firewall dependency.")
    if not actions:
        actions.append("Attach this summary to the M1 go/no-go evidence bundle and operations review.")
    return actions


def _markdown_cell(value: Any) -> str:
    text = _clean_text(value)
    return text.replace("|", "\\|") or "-"


def build_postgres_redis_ops_summary_markdown(report: Mapping[str, Any]) -> str:
    safe_report = redact_data(dict(report))
    if not isinstance(safe_report, Mapping):
        safe_report = {}
    lines = [
        "# PostgreSQL / Redis Operations Summary",
        "",
        f"- Status: `{_markdown_cell(safe_report.get('status'))}`",
        f"- Decision: `{_markdown_cell(safe_report.get('decision'))}`",
        "- Policy: no `.env`, no database rows, no Redis keys, no logs, no SSH execution.",
        "",
        "## Sections",
        "",
        "| Section | Status | Version |",
        "|---|---|---|",
    ]
    sections = _as_mapping(safe_report.get("sections"))
    for name, section in sections.items():
        if not isinstance(section, Mapping):
            continue
        lines.append(
            "| "
            f"{_markdown_cell(section.get('label') or name)} | "
            f"`{_markdown_cell(section.get('status'))}` | "
            f"`{_markdown_cell(section.get('version'))}` |"
        )

    blockers = _as_list(safe_report.get("blocked_reasons"))
    if blockers:
        lines.extend(["", "## Blocked Reasons", "", "| Section | Key | Finding |", "|---|---|---|"])
        for item in blockers:
            if not isinstance(item, Mapping):
                continue
            lines.append(
                "| "
                f"{_markdown_cell(item.get('section'))} | "
                f"{_markdown_cell(item.get('key'))} | "
                f"{_markdown_cell(item.get('finding'))} |"
            )

    degraded = _as_list(safe_report.get("degraded_reasons"))
    if degraded:
        lines.extend(["", "## Degraded Reasons", "", "| Section | Key | Finding |", "|---|---|---|"])
        for item in degraded:
            if not isinstance(item, Mapping):
                continue
            lines.append(
                "| "
                f"{_markdown_cell(item.get('section'))} | "
                f"{_markdown_cell(item.get('key'))} | "
                f"{_markdown_cell(item.get('finding'))} |"
            )

    lines.extend(["", "## Next Actions", ""])
    for item in _as_list(safe_report.get("next_actions")):
        lines.append(f"- {_markdown_cell(item)}")

    lines.extend(["", "## Boundaries", ""])
    boundaries = _as_mapping(safe_report.get("claim_boundaries"))
    for item in _as_list(boundaries.get("cannot_claim")):
        lines.append(f"- Cannot claim: {_markdown_cell(item)}")
    for item in _as_list(safe_report.get("not_proven_by_this_summary")):
        lines.append(f"- {_markdown_cell(item)}")
    return "\n".join(lines) + "\n"


def _path_arg(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else PROJECT_ROOT / path


def _read_json(path: Path | None, *, label: str) -> tuple[Mapping[str, Any] | None, dict[str, Any] | None]:
    if path is None:
        return None, None
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None, {
            "version": "unreadable_json",
            "status": "blocked",
            "blocked_reasons": [
                {
                    "key": f"{label}_json",
                    "finding": f"{label} JSON could not be read or parsed.",
                    "value_echoed": False,
                }
            ],
        }
    if not isinstance(payload, Mapping):
        return None, {
            "version": "invalid_json",
            "status": "blocked",
            "blocked_reasons": [
                {
                    "key": f"{label}_json",
                    "finding": f"{label} JSON must be an object.",
                    "value_echoed": False,
                }
            ],
        }
    return payload, None


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ops-status-json", type=_path_arg, default=None, help="check_postgres_redis_ops_status.py JSON output.")
    parser.add_argument("--live-probe-json", type=_path_arg, default=None, help="collect_postgres_redis_live_probe.py JSON output.")
    parser.add_argument("--recovery-record-json", type=_path_arg, default=None, help="check_postgres_redis_recovery_record.py JSON output.")
    parser.add_argument("--json", action="store_true", help="Print JSON. Default is Markdown.")
    parser.add_argument("--markdown", action="store_true", help="Print Markdown.")
    parser.add_argument("--output", type=_path_arg, default=None, help="Optional output path.")
    return parser.parse_args(list(argv) if argv is not None else None)


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(argv)
    ops_status, ops_error = _read_json(args.ops_status_json, label="ops_status")
    live_probe, live_error = _read_json(args.live_probe_json, label="live_probe")
    recovery_record, recovery_error = _read_json(args.recovery_record_json, label="recovery_record")
    report = build_postgres_redis_ops_summary_report(
        ops_status=ops_error or ops_status,
        live_probe=live_error or live_probe,
        recovery_record=recovery_error or recovery_record,
    )
    output_text = (
        json.dumps(report, ensure_ascii=False, indent=2)
        if args.json and not args.markdown
        else build_postgres_redis_ops_summary_markdown(report)
    )
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output_text + ("\n" if not output_text.endswith("\n") else ""), encoding="utf-8")
    else:
        print(output_text, end="" if output_text.endswith("\n") else "\n")
    return 2 if report["status"] == "blocked" else 0


if __name__ == "__main__":
    raise SystemExit(main())
